name: VoidTotem
version: '${project.version}'
main: de.rapha149.voidtotem.VoidTotem
authors: [ Rapha149 ]
description: Use a totem to save you from the void!
website: https://github.com/Rapha149/VoidTotem
