name: VoidTotem
version: '${project.version}'
main: de.rapha149.voidtotem.VoidTotem
authors: [ Rapha149 ]
description: Use a totem to save you from the void!
api-version: 1.13
website: https://github.com/Rapha149/VoidTotem

commands:
  voidtotemreload:
    permission: voidtotem.reload

permissions:
  voidtotem.*:
    children:
      voidtotem: true
  voidtotem.reload:
    children:
      voidtotem: true